---
deployment:
  targets:
    myapp:
      domain: binarahmatika-group.com
      path: /public_html
      branch: main
      url: https://github.com/panjihanum/binarahmatika-web.git
      build_command: |
        npm install --production
        npm run build
      restart_reload_command: |
        pkill -f "node app.js"
      post_deploy_script: |
        echo "Deployment completed successfully!"

features:
  - mysql
  - nodejs_selector
